name: Pr

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  id-token: write # for creating OIDC tokens for signing.

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
        
      - name: Setup JFrog CLI
        id: setup-cli
        uses: jfrog/setup-jfrog-cli@v4.9.1
        env: 
          JF_URL: https://${{ vars.JF_URL }}/
          JF_PROJECT: carmit
        with:
            oidc-provider-name: github-oidc

      - name: Setup Tooling
        uses: jdx/mise-action@d6e32c1796099e0f1f3ac741c220a8b7eae9e5dd
        with:
          install: true
          cache: true
          experimental: true

      - name: setup jfrog npm repo
        run: |
          npm config set registry https://ctoa.jfrog.io/artifactory/api/npm/carmit-carmit-npm-virtual/
          npm config set //ctoa.jfrog.io/artifactory/api/npm/carmit-carmit-npm-virtual/:_authToken ${{ steps.setup-cli.outputs.oidc-token }}
      

      - name: Run Checks
        run: |
          mise run setup
          mise run lint
          mise run test
          mise run build
